name: Coverage with Codecov

on:
  # Trigger on push to branches "main" and "develop".
  push:
    branches:
      - main
      - develop
  # Trigger on pull request events for PRs that have "main" as their target branch
  pull_request:
      branches:
        - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
